### ISSUE TITLE
[Feature] Implement Button Functionality

### ISSUE THREAD

**Issue by mike10911** [HackBeanpot/internal-tools#92]
### TODO

With dummy data 

- [ ]  When you click the 'sort' button it should display table of sorted hackers into cabins
- [ ] button should call the sorting function and store the output in state
- [ ] reference to the design: #91

**Comment by yanDavid21** [comment]
more context would be good! does this button run front end code to sort or does it call an endpoint
